### ISSUE TITLE
Remove mentions of leaf

### ISSUE THREAD

**Issue by svenstaro** [anowell/are-we-learning-yet#21]
leaf has been officially deprecated by their devs. It should not be mentioned anymore.

**Comment by anowell** [comment]
[Wow! I am slow at getting to this!]

I rewrote the overview on the neural networks page to decrease the emphasis on Leaf. I'm not ready to remove it completely because:

- Leaf had popularity by some measure - it managed to appear pretty high on lists of most-starred ML frameworks (irrespective of language)
- Leaf may be a good source of inspiration or starting point for future rust neural networks (and even provide historical context to Juice, though it remains to be seen if Juice can pick up where Leaf left off since almost all "activity" over the last 6 months has been on docs)
- Most of the crates listed on AWLY, including Leaf, are in some state between short-lived experiments and barely maintained projects - which is an honest characterization of the ecosystem. I expect the bar for crate visibility to rise in parallel with the ecosystem maturity,

I'd also like to revist how to promote actively developed/maintained more clearly (higher in listings, or with badges or other prominence in the design). That would be another way in which leaf is deemphasize, but I don't have an immediate plans to work on that.
